import type { Story } from "@/interfaces/story";

export const storiesService = (): Story[] => {
	return [
		{
			author: "Rikelvi Capellán",
			category: "Short story",
			content: [
				{
					title: "Prefacio",
					paragraphs: [
						"Si alguna vez te han hecho esa pregunta y con total obviedad contestas que sí, puede ser que te equivoques. Si buscas una respuesta a tal pregunta, acompáñame en este relato.",
						'"¡Corre, alcanza tus sueños! Un botón mágico no caerá del cielo para transformarte la vida."',
					],
				},
				{
					title: "Relato",
					paragraphs: [
						"Un joven estaba pasando por una situación grave, donde buscaba algo que él soñaba ser, pero cada vez que se veía en la situación de que sentía que estaba avanzando un poco, venía alguien y le arrebataba ese ápice de esperanza. A ese joven le daban todo lo que él pedía para poder alcanzar el sueño deseado, pero él no se esforzaba por alcanzar sus logros. El joven quería dinero, fama y ser reconocido por una multitud, siguiendo lo fácil. Él esperaba que un día bajara un botón mágico del cielo para pulsarlo y que su vida se transforme en un segundo.",
						"Un día, caminando por la calle, se topa con un anciano no muy bien vestido, mal oliente, lleno de lodo en sus botas.",
						"El anciano detiene al joven.",
						"—Toma estos $5,000 dólares, joven, cómprate algo —mirándolo a los ojos—.",
						"El joven lo rechaza y le recalca en su cara que es él que lo necesita, a modo de burla.",
						"Pasados dos días, el joven se entera de que el anciano tiene una mansión, 3 autos lujosos, villas en todo el país y varias granjas administradas por él mismo. Por lo que, toma la decisión de ir a su casa.",
						"Llega a la casa del anciano y este, muy amablemente, lo deja pasar. Lo manda a sentar y, sin esperar a que se sentara, pregunta:",
						"—¿Viniste por los $5,000 dólares? —ceñudo.",
						"—No —contesta el joven sin dejar espacios en la conversación.",
						"El viejo espera unos segundos y lanza la intriga:",
						"—¿Por qué no los aceptaste? —preguntó el anciano, deseando que el joven le sea honesto.",
						"—Porque no los necesitaba —contesta el joven, negando con la cabeza, con el ceño fruncido, mintiendo.",
						"—¿A qué has venido? —pregunta el anciano. Sin embargo, él sabía la razón. Era un anciano muy sabio.",
						"—¿Cómo consiguió usted todo lo que tiene? —indagó el joven, en busca de la respuesta a su necesidad.",
						"El anciano se para, sin hablar, pasa a la cocina de su hogar y busca un poco de leche para tomar. A lo lejos le pregunta al joven si desea un poco. A lo que el joven contesta que no le gusta la leche.",
						"El anciano se devuelve a donde estaba sentado y lanza la pregunta al joven que está entusiasmado por saber el secreto de los logros del anciano:",
						"—¿Las vacas dan leche?",
						"El joven, extraño, contesta con obviedad y burla, y le dice que sí.",
						"—¡No! —dice el anciano, apagando su burla en un instante—. Ellas no la dan.",
						"—¡¿Qué dices?! —espeta el joven—. ¿Quién te dio la leche que estás bebiendo si no?",
						'—Escucha, joven —dice el anciano con mucha tranquilidad—. Tiempo atrás había un joven al que se le dificultaban las cosas tanto como a ti ahora mismo. Él, como quien no quiere la cosa, se levantaba a las 12:00 del mediodía, estudió por obligación y no se interesó en la universidad. Pues, le daban todo lo que él quería. Hasta que un día sus padres fallecieron en un trágico accidente automovilístico. Desde ahí, ese joven comenzó a vivir la otra cara de la vida. Le surgió la necesidad de trabajar, no podía tener los tenis que quería al instante, todos sus amigos lo despreciaban por falta de bienes. Sin embargo, pasados unos meses, se encontró con alguien que le dijo: "Si quieres leche, no esperes a que la vaca venga a tu casa y se ordeñe ella misma para darte la leche. Anda con una cubeta al campo y ordéñala con tus manos, pon un puesto aquí al lado de mi negocio y véndela. Luego agradéceme". Aquel joven no lo entendió del todo al principio, pero se fue a su casa pensativo.',
						"El anciano se detuvo de contar la historia y pasó nuevamente a la cocina a llevar la taza en la que estaba bebiendo leche. El joven, intrigado, no se aguantó y le preguntó:",
						"—¿Ese joven era usted?",
						"—A la mañana siguiente —continúa el anciano, volviendo a su asiento—, luego de haberlo pensado bastante, se levantó y fue donde un granjero. Con el poco dinero que tenía, por la herencia de sus padres, le compró una vaca y un toro al granjero por $400 dólares.",
						"El anciano hace una pausa...",
						"—¿Y luego qué? —preguntó el joven con más intriga.",
						"—¿Sabes cuántas vacas tiene ese joven hoy en día siendo un anciano? —cuestiona el anciano al joven.",
						"—¿Cuántas? —indaga el joven.",
						"—Más de 1,000 vacas, con villas en todo el país, 3 carros lujosos y esta mansión donde estamos ahora mismo —contesta el anciano—. Sin embargo, eso no es lo importante.",
						"—¿De qué hablas? ¿Por qué no, si consiguió todo esto con sus manos?",
						"—¿Cuántos años tienes, jovencito? —preguntó el anciano, dejando de lado sus dos preguntas.",
						"—Tengo 19 —contestó el joven.",
						"—La parte importante fue que —continuó el anciano, contestando las cuestiones del joven—, en esa mañana, aquel joven tomó la decisión de entender que las vacas no dan leche, sino que es la persona que tiene que tomar la iniciativa de ir a donde está la vaca y saciar su necesidad. Así mismo, tú puedes levantarte temprano y tomar la decisión de ir tras eso que sueñas y no esperar a que caiga del cielo mágicamente. Así no es la vida, joven.",
						"—Usted fue muy sabio al tomar esa decisión —dice el joven al anciano.",
						"—Tú también puedes, joven —le contesta el anciano—. Anda, toma los $5,000 dólares, inviértelos en algo y sácale provecho. ¡Que Dios te acompañe!",
						"Y así se despidió el anciano del joven. El joven se fue a su casa y lo pensó bastante.",
						"...",
						'7 años después, a los 26 años del joven, él regresa donde el anciano, ya más mayor, montado en un hermoso auto BMW V3 del año y vestido como aquel joven de 19 años tanto quería. El anciano le abre y sin pretextos lo deja pasar. Sin entrar bien a la mansión, el joven abraza fuertemente al anciano y solamente le dice... "¡gracias!" con lágrimas en los ojos...',
					],
				},
			],
			description:
				"Si alguna vez te han hecho esa pregunta y con total obviedad contestas que sí, puede ser que te equivoques. Si buscas una respuesta a tal pregunta, acompáñame en este relato.",
			lang: "es",
			pageTitle: "las-vacas-dan-leche-relato-i",
			tags: [
				"anciano",
				"corta",
				"fama",
				"historia",
				"joven",
				"leche",
				"moraleja",
				"relato",
				"riquezas",
				"sueños",
				"vaca",
			],
			timestamp: "8/May/2024",
			title: "¿Las Vacas Dan Leche? [Relato I]",
		},
	];
};
